#TABLE 1 : TEAMS

In [1]:
import requests
url = "https://api-web.nhle.com/v1/standings/now"
response = requests.get(url)
data = response.json()
data

{'wildCardIndicator': True,
 'standingsDateTimeUtc': '2026-09-08T10:43:30Z',
 'standings': [{'clinchIndicator': 'p',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 1,
   'divisionName': 'Central',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 99,
   'goalDifferentialPctg': 1.207317,
   'goalAgainst': 203,
   'goalFor': 302,
   'goalsForPctg': 3.682927,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 49,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 157,
   'homeLosses': 9,
   'homeOtLosses': 6,
   'homePoints': 58,
   'homeRegulationPlusOtWins': 25,
   'homeRegulationWins': 25,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 14,
   'l10GoalsAgainst': 20,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 3,
   'leagueL10Sequence': 4,
   'leagueRoadSequence': 1,
   'leagueSequence': 1,
   'losses': 16,
   'otLosses': 11,
   'placeName': {'default': 'Colorado'},
   'pointPctg': 0.737805,
   'points': 121,
   'regulationPlusOtWinPctg': 0.621951,
   'regulationPlusOtWins': 51,
   'regulationWinPctg': 0.585366,
   'regulationWins': 48,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 50,
   'roadGoalsAgainst': 95,
   'roadGoalsFor': 145,
   'roadLosses': 7,
   'roadOtLosses': 5,
   'roadPoints': 63,
   'roadRegulationPlusOtWins': 26,
   'roadRegulationWins': 23,
   'roadTies': 0,
   'roadWins': 29,
   'seasonId': 20252026,
   'shootoutLosses': 6,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 3,
   'teamName': {'default': 'Colorado Avalanche',
    'fr': 'Avalanche du Colorado'},
   'teamCommonName': {'default': 'Avalanche'},
   'teamAbbrev': {'default': 'COL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
   'ties': 0,
   'waiversSequence': 32,
   'wildcardSequence': 0,
   'winPctg': 0.670732,
   'wins': 55},
  {'clinchIndicator': 'z',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 3,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'M',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 2,
   'divisionName': 'Metropolitan',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 56,
   'goalDifferentialPctg': 0.682927,
   'goalAgainst': 240,
   'goalFor': 296,
   'goalsForPctg': 3.609756,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 35,
   'homeGoalsAgainst': 126,
   'homeGoalsFor': 161,
   'homeLosses': 10,
   'homeOtLosses': 2,
   'homePoints': 60,
   'homeRegulationPlusOtWins': 27,
   'homeRegulationWins': 20,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 12,
   'l10GoalsAgainst': 27,
   'l10GoalsFor': 39,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 7,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 1,
   'leagueL10Sequence': 3,
   'leagueRoadSequence': 5,
   'leagueSequence': 2,
   'losses': 22,
   'otLosses': 7,
   'placeName': {'default': 'Carolina', 'fr': 'Caroline'},
   'pointPctg': 0.689024,
   'points': 113,
   'regulationPlusOtWinPctg': 0.585366,
   'regulationPlusOtWins': 48,
   'regulationWinPctg': 0.47561,
   'regulationWins': 39,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 21,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 135,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 21,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 5,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Carolina Hurricanes',
    'fr': 'Hurricanes de la Caroline'},
   'teamCommonName': {'default': 'Hurricanes'},
   'teamAbbrev': {'default': 'CAR'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg',
   'ties': 0,
   'waiversSequence': 31,
   'wildcardSequence': 0,
   'winPctg': 0.646341,
   'wins': 53},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 2,
   'divisionName': 'Central',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 53,
   'goalDifferentialPctg': 0.646341,
   'goalAgainst': 226,
   'goalFor': 279,
   'goalsForPctg': 3.402439,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 23,
   'homeGoalsAgainst': 112,
   'homeGoalsFor': 135,
   'homeLosses': 11,
   'homeOtLosses': 4,
   'homePoints': 56,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 28,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 5,
   'leagueL10Sequence': 5,
   'leagueRoadSequence': 2,
   'leagueSequence': 3,
   'losses': 20,
   'otLosses': 12,
   'placeName': {'default': 'Dallas'},
   'pointPctg': 0.682927,
   'points': 112,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 30,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 144,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 6,
   'streakCode': 'W',
   'streakCount': 5,
   'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'},
   'teamCommonName': {'default': 'Stars'},
   'teamAbbrev': {'default': 'DAL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg',
   'ties': 0,
   'waiversSequence': 30,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'y',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 6,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 3,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 3,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 47,
   'goalDifferentialPctg': 0.573171,
   'goalAgainst': 241,
   'goalFor': 288,
   'goalsForPctg': 3.512195,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 30,
   'homeGoalsAgainst': 119,
   'homeGoalsFor': 149,
   'homeLosses': 10,
   'homeOtLosses': 5,
   'homePoints': 57,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 22,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 34,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 4,
   'leagueL10Sequence': 12,
   'leagueRoadSequence': 6,
   'leagueSequence': 4,
   'losses': 23,
   'otLosses': 9,
   'placeName': {'default': 'Buffalo'},
   'pointPctg': 0.664634,
   'points': 109,
   'regulationPlusOtWinPctg': 0.54878,
   'regulationPlusOtWins': 45,
   'regulationWinPctg': 0.512195,
   'regulationWins': 42,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 122,
   'roadGoalsFor': 139,
   'roadLosses': 13,
   'roadOtLosses': 4,
   'roadPoints': 52,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 20,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 1,
   'shootoutWins': 5,
   'streakCode': 'OT',
   'streakCount': 1,
   'teamName': {'default': 'Buffalo Sabres', 'fr': 'Sabres de Buffalo'},
   'teamCommonName': {'default': 'Sabres'},
   'teamAbbrev': {'default': 'BUF'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg',
   'ties': 0,
   'waiversSequence': 29,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 5,
   'conferenceL10Sequence': 12,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 6,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 59,
   'goalDifferentialPctg': 0.719512,
   'goalAgainst': 231,
   'goalFor': 290,
   'goalsForPctg': 3.536585,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 22,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 137,
   'homeLosses': 14,
   'homeOtLosses': 1,
   'homePoints': 53,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': -4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 26,
   'l10Losses': 5,
   'l10OtLosses': 0,
   'l10Points': 10,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 8,
   'leagueL10Sequence': 21,
   'leagueRoadSequence': 4,
   'leagueSequence': 5,
   'losses': 26,
   'otLosses': 6,
   'placeName': {'default': 'Tampa Bay'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.560976,
   'regulationPlusOtWins': 46,
   'regulationWinPctg': 0.487805,
   'regulationWins': 40,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 37,
   'roadGoalsAgainst': 116,
   'roadGoalsFor': 153,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 21,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 2,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Tampa Bay Lightning',
    'fr': 'Lightning de Tampa Bay'},
   'teamCommonName': {'default': 'Lightning'},
   'teamAbbrev': {'default': 'TBL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg',
   'ties': 0,
   'waiversSequence': 28,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 7,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 4,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 5,
   'divisionL10Sequence': 1,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 1,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 27,
   'goalDifferentialPctg': 0.329268,
   'goalAgainst': 256,
   'goalFor': 283,
   'goalsForPctg': 3.45122,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 10,
   'homeGoalsAgainst': 127,
   'homeGoalsFor': 137,
   'homeLosses': 15,
   'homeOtLosses': 2,
   'homePoints': 50,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 17,
   'homeTies': 0,
   'homeWins': 24,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 24,
   'l10GoalsFor': 28,
   'l10Losses': 3,
   'l10OtLosses': 0,
   'l10Points': 14,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 12,
   'leagueL10Sequence': 7,
   'leagueRoadSequence': 3,
   'leagueSequence': 6,
   'losses': 24,
   'otLosses': 10,
   'placeName': {'default': 'Montréal'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.414634,
   'regulationWins': 34,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 129,
   'roadGoalsFor': 146,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Montréal Canadiens',
    'fr': 'Canadiens de Montréal'},
   'teamCommonName': {'default': 'Canadiens'},
   'teamAbbrev': {'default': 'MTL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg',
   'ties': 0,
   'waiversSequence': 27,
   'wildcardSequence': 0,
   'winPctg': 0.585366,
   'wins': 48},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 7,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 4,
   'divisionName': 'Central',
   'divisionRoadSequence': 3,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 240,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 15,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 130,
   'homeLosses': 10,
   'homeOtLosses': 8,
   'homePoints': 54,
   'homeRegulationPlusOtWins': 19,
   'homeRegulationWins': 14,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 32,
   'l10GoalsFor': 36,
   'l10Losses': 4,
   'l10OtLosses': 0,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 7,
   'leagueL10Sequence': 14,
   'leagueRoadSequence': 9,
   'leagueSequence': 7,
   'losses': 24,
   'otLosses': 12,
   'placeName': {'default': 'Minnesota'},
   'pointPctg': 0.634146,
   'points': 104,
   'regulationPlusOtWinPctg': 0.512195,
   'regulationPlusOtWins': 42,
   'regulationWinPctg': 0.378049,
   'regulationWins': 31,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 125,
   'roadGoalsFor': 142,
   'roadLosses': 14,
   'roadOtLosses': 4,
   'roadPoints': 50,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 23,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'},
   'teamCommonName': {'default': 'Wild'},
   'teamAbbrev': {'default': 'MIN'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg',
   'ties': 0,
   'waiversSequence': 26,
   'wildcardSequence': 0,
   'winPctg': 0.560976,
   'wins': 46},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 8,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 13,
   'conferenceSequence': 5,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 4,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 6,
   'divisionSequence': 4,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 22,
   'goalDifferentialPctg': 0.268293,
   'goalAgainst': 250,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 40,
   'homeGoalsAgainst': 105,
   'homeGoalsFor': 145,
   'homeLosses': 11,
   'homeOtLosses': 1,
   'homePoints': 59,
   'homeRegulationPlusOtWins': 28,
   'homeRegulationWins': 23,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 32,
   'l10Losses': 3,
   'l10OtLosses': 2,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 4,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 2,
   'leagueL10Sequence': 16,
   'leagueRoadSequence': 21,
   'leagueSequence': 8,
   'losses': 27,
   'otLosses': 10,
   'placeName': {'default': 'Boston'},
   'pointPctg': 0.609756,
   'points': 100,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.402439,
   'regulationWins': 33,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': -18,
   'roadGoalsAgainst': 145,
   'roadGoalsFor': 127,
   'roadLosses': 16,
   'roadOtLosses': 9,
   'roadPoints': 41,
   'roadRegulationPlusOtWins': 13,
   'roadRegulationWins': 10,
   'roadTies': 0,
   'roadWins': 16,
   'seasonId': 20252026,
   'shootoutLosses': 3,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 2,
   'teamName': {'default': 'Boston Bruins', 'fr': 'Bruins de Boston'},
   'teamCommonName': {'default': 'Bruins'},
   'teamAbbrev': {'default': 'BOS'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg?season=20252026',
   'ties': 0,
   'waiversSequence': 25,
   'wildcardSequence': 1,
   'winPctg': 0.54878,
   'wins': 45},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 6,
   'conferenceL10Sequence': 5,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 7,
   'conferenceSequence': 6,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 4,
   'divisionL10Sequence': 2,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 4,
   'divisionSequence': 5,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 246,
   'goalFor': 278,
   'goalsForPctg': 3.390244,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 31,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 139,
   'homeLosses': 12,
   'homeOtLosses': 6,
   'homePoints': 52,
   'homeRegulationPlusOtWins': 21,
   'homeRegulationWins': 21,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 10,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 36,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 9,
   'leagueL10Sequence': 10,
   'leagueRoadSequence': 11,
   'leagueSequence': 9,
   'losses': 27,
   'otLosses': 11,
   'placeName': {'default': 'Ottawa'},
   'pointPctg': 0.603659,
   'points': 99,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 1,
   'roadGoalsAgainst': 138,
   'roadGoalsFor': 139,
   'roadLosses': 15,
   'roadOtLosses': 5,
   'roadPoints': 47,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 17,

In [5]:
team_abbrev=data['standings'][0]['teamAbbrev']['default']
team_name=data['standings'][0]['teamName']['default']
conference_name=data['standings'][0]['conferenceName']
division_name=data['standings'][0]['divisionName']
logo_url=data['standings'][0]['teamLogo']

In [6]:
records = []
for team in data['standings']:
        records.append({
         'division_name': team['divisionName'],
         'conference_name': team['conferenceName'],
         'team_name': team['teamName']['default'],
         'team_abbrev': team['teamAbbrev']['default'],
         'logo_url': team['teamLogo']
     })
records

[{'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'Colorado Avalanche',
  'team_abbrev': 'COL',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'Carolina Hurricanes',
  'team_abbrev': 'CAR',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg'},
 {'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'Dallas Stars',
  'team_abbrev': 'DAL',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Buffalo Sabres',
  'team_abbrev': 'BUF',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Tampa Bay Lightning',
  'team_abbrev': 'TBL',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Montréal Canadiens',
  'team_abbrev': 'MTL',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg'},
 {'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'Minnesota Wild',
  'team_abbrev': 'MIN',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Boston Bruins',
  'team_abbrev': 'BOS',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Ottawa Senators',
  'team_abbrev': 'OTT',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/OTT_light.svg'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'Pittsburgh Penguins',
  'team_abbrev': 'PIT',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/PIT_light.svg'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'Philadelphia Flyers',
  'team_abbrev': 'PHI',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/PHI_light.svg'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'Washington Capitals',
  'team_abbrev': 'WSH',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/WSH_secondary_light.svg'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'Vegas Golden Knights',
  'team_abbrev': 'VGK',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/VGK_light.svg'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'Edmonton Oilers',
  'team_abbrev': 'EDM',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/EDM_light.svg'},
 {'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'Utah Mammoth',
  'team_abbrev': 'UTA',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/UTA_light.svg?season=20252026'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Detroit Red Wings',
  'team_abbrev': 'DET',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/DET_light.svg?season=20252026'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'Columbus Blue Jackets',
  'team_abbrev': 'CBJ',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CBJ_light.svg'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'Anaheim Ducks',
  'team_abbrev': 'ANA',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/ANA_light.svg'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'New York Islanders',
  'team_abbrev': 'NYI',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NYI_light.svg'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'Los Angeles Kings',
  'team_abbrev': 'LAK',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/LAK_light.svg'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'New Jersey Devils',
  'team_abbrev': 'NJD',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NJD_light.svg'},
 {'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'St. Louis Blues',
  'team_abbrev': 'STL',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/STL_light.svg?season=20252026'},
 {'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'Nashville Predators',
  'team_abbrev': 'NSH',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NSH_light.svg'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'San Jose Sharks',
  'team_abbrev': 'SJS',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/SJS_light.svg'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Florida Panthers',
  'team_abbrev': 'FLA',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/FLA_light.svg'},
 {'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'Winnipeg Jets',
  'team_abbrev': 'WPG',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/WPG_light.svg'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'Seattle Kraken',
  'team_abbrev': 'SEA',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/SEA_light.svg'},
 {'division_name': 'Atlantic',
  'conference_name': 'Eastern',
  'team_name': 'Toronto Maple Leafs',
  'team_abbrev': 'TOR',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/TOR_light.svg'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'Calgary Flames',
  'team_abbrev': 'CGY',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CGY_light.svg'},
 {'division_name': 'Metropolitan',
  'conference_name': 'Eastern',
  'team_name': 'New York Rangers',
  'team_abbrev': 'NYR',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/NYR_light.svg'},
 {'division_name': 'Central',
  'conference_name': 'Western',
  'team_name': 'Chicago Blackhawks',
  'team_abbrev': 'CHI',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CHI_light.svg?season=20252026'},
 {'division_name': 'Pacific',
  'conference_name': 'Western',
  'team_name': 'Vancouver Canucks',
  'team_abbrev': 'VAN',
  'logo_url': 'https://assets.nhle.com/logos/nhl/svg/VAN_light.svg'}]

In [7]:
import pymysql
conn=pymysql.connect(host='localhost',
                     user='root',
                     password='13849#Datasci',
                     database='proj1'
                     )
cursor=conn.cursor()

In [8]:

cursor.execute("""
CREATE TABLE IF NOT EXISTS teams (
    team_id INT AUTO_INCREMENT PRIMARY KEY,
    team_abbrev VARCHAR(10) UNIQUE,
    team_name VARCHAR(100),
    conference_name VARCHAR(100),
    division_name VARCHAR(100),
    logo_url TEXT
)

""")

conn.commit()

In [11]:
INSERT_QUERY = """
INSERT IGNORE INTO teams
(team_abbrev, team_name, conference_name, division_name, logo_url)
VALUES (%s, %s, %s, %s, %s)
"""

In [12]:
for i in records:
    
    values = (
        i['team_abbrev'],
        i['team_name'],
        i['conference_name'],
        i['division_name'],
        i['logo_url']
    )

    cursor.execute(INSERT_QUERY, values)

conn.commit()
cursor.execute("SELECT * FROM teams")
rows = cursor.fetchall()

In [10]:
import pandas as pd
df=pd.read_sql_query("select * from teams",conn)
df

C:\Users\dines\AppData\Local\Temp\ipykernel_20440\3301588069.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("select * from teams",conn)

,team_id,team_abbrev,team_name,conference_name,division_name,logo_url
0,1,Central,Western,Colorado Avalanche,COL,https://assets.nhle.com/logos/nhl/svg/COL_ligh...
1,3,COL,Colorado Avalanche,Western,Central,https://assets.nhle.com/logos/nhl/svg/COL_ligh...
2,4,CAR,Carolina Hurricanes,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/CAR_ligh...
3,5,DAL,Dallas Stars,Western,Central,https://assets.nhle.com/logos/nhl/svg/DAL_ligh...
4,6,BUF,Buffalo Sabres,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/BUF_ligh...
5,7,TBL,Tampa Bay Lightning,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/TBL_ligh...
6,8,MTL,Montréal Canadiens,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...
7,9,MIN,Minnesota Wild,Western,Central,https://assets.nhle.com/logos/nhl/svg/MIN_ligh...
8,10,BOS,Boston Bruins,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/BOS_ligh...
9,11,OTT,Ottawa Senators,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/OTT_ligh...
10,12,PIT,Pittsburgh Penguins,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/PIT_ligh...
11,13,PHI,Philadelphia Flyers,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/PHI_ligh...
12,14,WSH,Washington Capitals,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/WSH_seco...
13,15,VGK,Vegas Golden Knights,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/VGK_ligh...
14,16,EDM,Edmonton Oilers,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/EDM_ligh...
15,17,UTA,Utah Mammoth,Western,Central,https://assets.nhle.com/logos/nhl/svg/UTA_ligh...
16,18,DET,Detroit Red Wings,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/DET_ligh...
17,19,CBJ,Columbus Blue Jackets,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/CBJ_ligh...
18,20,ANA,Anaheim Ducks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/ANA_ligh...
19,21,NYI,New York Islanders,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NYI_ligh...
20,22,LAK,Los Angeles Kings,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/LAK_ligh...
21,23,NJD,New Jersey Devils,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NJD_ligh...
22,24,STL,St. Louis Blues,Western,Central,https://assets.nhle.com/logos/nhl/svg/STL_ligh...
23,25,NSH,Nashville Predators,Western,Central,https://assets.nhle.com/logos/nhl/svg/NSH_ligh...
24,26,SJS,San Jose Sharks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/SJS_ligh...
25,27,FLA,Florida Panthers,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/FLA_ligh...
26,28,WPG,Winnipeg Jets,Western,Central,https://assets.nhle.com/logos/nhl/svg/WPG_ligh...
27,29,SEA,Seattle Kraken,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/SEA_ligh...
28,30,TOR,Toronto Maple Leafs,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/TOR_ligh...
29,31,CGY,Calgary Flames,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/CGY_ligh...
30,32,NYR,New York Rangers,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NYR_ligh...
31,33,CHI,Chicago Blackhawks,Western,Central,https://assets.nhle.com/logos/nhl/svg/CHI_ligh...
32,34,VAN,Vancouver Canucks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/VAN_ligh...

In [ ]:
# TABLE 2: STANDINGS

In [1]:
import requests
url = "https://api-web.nhle.com/v1/standings/now"
response = requests.get(url)
data = response.json()
data

{'wildCardIndicator': True,
 'standingsDateTimeUtc': '2026-09-06T15:35:46Z',
 'standings': [{'clinchIndicator': 'p',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 1,
   'divisionName': 'Central',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 99,
   'goalDifferentialPctg': 1.207317,
   'goalAgainst': 203,
   'goalFor': 302,
   'goalsForPctg': 3.682927,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 49,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 157,
   'homeLosses': 9,
   'homeOtLosses': 6,
   'homePoints': 58,
   'homeRegulationPlusOtWins': 25,
   'homeRegulationWins': 25,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 14,
   'l10GoalsAgainst': 20,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 3,
   'leagueL10Sequence': 4,
   'leagueRoadSequence': 1,
   'leagueSequence': 1,
   'losses': 16,
   'otLosses': 11,
   'placeName': {'default': 'Colorado'},
   'pointPctg': 0.737805,
   'points': 121,
   'regulationPlusOtWinPctg': 0.621951,
   'regulationPlusOtWins': 51,
   'regulationWinPctg': 0.585366,
   'regulationWins': 48,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 50,
   'roadGoalsAgainst': 95,
   'roadGoalsFor': 145,
   'roadLosses': 7,
   'roadOtLosses': 5,
   'roadPoints': 63,
   'roadRegulationPlusOtWins': 26,
   'roadRegulationWins': 23,
   'roadTies': 0,
   'roadWins': 29,
   'seasonId': 20252026,
   'shootoutLosses': 6,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 3,
   'teamName': {'default': 'Colorado Avalanche',
    'fr': 'Avalanche du Colorado'},
   'teamCommonName': {'default': 'Avalanche'},
   'teamAbbrev': {'default': 'COL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
   'ties': 0,
   'waiversSequence': 32,
   'wildcardSequence': 0,
   'winPctg': 0.670732,
   'wins': 55},
  {'clinchIndicator': 'z',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 3,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'M',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 2,
   'divisionName': 'Metropolitan',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 56,
   'goalDifferentialPctg': 0.682927,
   'goalAgainst': 240,
   'goalFor': 296,
   'goalsForPctg': 3.609756,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 35,
   'homeGoalsAgainst': 126,
   'homeGoalsFor': 161,
   'homeLosses': 10,
   'homeOtLosses': 2,
   'homePoints': 60,
   'homeRegulationPlusOtWins': 27,
   'homeRegulationWins': 20,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 12,
   'l10GoalsAgainst': 27,
   'l10GoalsFor': 39,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 7,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 1,
   'leagueL10Sequence': 3,
   'leagueRoadSequence': 5,
   'leagueSequence': 2,
   'losses': 22,
   'otLosses': 7,
   'placeName': {'default': 'Carolina', 'fr': 'Caroline'},
   'pointPctg': 0.689024,
   'points': 113,
   'regulationPlusOtWinPctg': 0.585366,
   'regulationPlusOtWins': 48,
   'regulationWinPctg': 0.47561,
   'regulationWins': 39,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 21,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 135,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 21,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 5,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Carolina Hurricanes',
    'fr': 'Hurricanes de la Caroline'},
   'teamCommonName': {'default': 'Hurricanes'},
   'teamAbbrev': {'default': 'CAR'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg',
   'ties': 0,
   'waiversSequence': 31,
   'wildcardSequence': 0,
   'winPctg': 0.646341,
   'wins': 53},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 2,
   'divisionName': 'Central',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 53,
   'goalDifferentialPctg': 0.646341,
   'goalAgainst': 226,
   'goalFor': 279,
   'goalsForPctg': 3.402439,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 23,
   'homeGoalsAgainst': 112,
   'homeGoalsFor': 135,
   'homeLosses': 11,
   'homeOtLosses': 4,
   'homePoints': 56,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 28,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 5,
   'leagueL10Sequence': 5,
   'leagueRoadSequence': 2,
   'leagueSequence': 3,
   'losses': 20,
   'otLosses': 12,
   'placeName': {'default': 'Dallas'},
   'pointPctg': 0.682927,
   'points': 112,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 30,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 144,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 6,
   'streakCode': 'W',
   'streakCount': 5,
   'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'},
   'teamCommonName': {'default': 'Stars'},
   'teamAbbrev': {'default': 'DAL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg',
   'ties': 0,
   'waiversSequence': 30,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'y',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 6,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 3,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 3,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 47,
   'goalDifferentialPctg': 0.573171,
   'goalAgainst': 241,
   'goalFor': 288,
   'goalsForPctg': 3.512195,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 30,
   'homeGoalsAgainst': 119,
   'homeGoalsFor': 149,
   'homeLosses': 10,
   'homeOtLosses': 5,
   'homePoints': 57,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 22,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 34,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 4,
   'leagueL10Sequence': 12,
   'leagueRoadSequence': 6,
   'leagueSequence': 4,
   'losses': 23,
   'otLosses': 9,
   'placeName': {'default': 'Buffalo'},
   'pointPctg': 0.664634,
   'points': 109,
   'regulationPlusOtWinPctg': 0.54878,
   'regulationPlusOtWins': 45,
   'regulationWinPctg': 0.512195,
   'regulationWins': 42,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 122,
   'roadGoalsFor': 139,
   'roadLosses': 13,
   'roadOtLosses': 4,
   'roadPoints': 52,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 20,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 1,
   'shootoutWins': 5,
   'streakCode': 'OT',
   'streakCount': 1,
   'teamName': {'default': 'Buffalo Sabres', 'fr': 'Sabres de Buffalo'},
   'teamCommonName': {'default': 'Sabres'},
   'teamAbbrev': {'default': 'BUF'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg',
   'ties': 0,
   'waiversSequence': 29,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 5,
   'conferenceL10Sequence': 12,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 6,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 59,
   'goalDifferentialPctg': 0.719512,
   'goalAgainst': 231,
   'goalFor': 290,
   'goalsForPctg': 3.536585,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 22,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 137,
   'homeLosses': 14,
   'homeOtLosses': 1,
   'homePoints': 53,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': -4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 26,
   'l10Losses': 5,
   'l10OtLosses': 0,
   'l10Points': 10,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 8,
   'leagueL10Sequence': 21,
   'leagueRoadSequence': 4,
   'leagueSequence': 5,
   'losses': 26,
   'otLosses': 6,
   'placeName': {'default': 'Tampa Bay'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.560976,
   'regulationPlusOtWins': 46,
   'regulationWinPctg': 0.487805,
   'regulationWins': 40,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 37,
   'roadGoalsAgainst': 116,
   'roadGoalsFor': 153,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 21,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 2,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Tampa Bay Lightning',
    'fr': 'Lightning de Tampa Bay'},
   'teamCommonName': {'default': 'Lightning'},
   'teamAbbrev': {'default': 'TBL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg',
   'ties': 0,
   'waiversSequence': 28,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 7,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 4,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 5,
   'divisionL10Sequence': 1,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 1,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 27,
   'goalDifferentialPctg': 0.329268,
   'goalAgainst': 256,
   'goalFor': 283,
   'goalsForPctg': 3.45122,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 10,
   'homeGoalsAgainst': 127,
   'homeGoalsFor': 137,
   'homeLosses': 15,
   'homeOtLosses': 2,
   'homePoints': 50,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 17,
   'homeTies': 0,
   'homeWins': 24,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 24,
   'l10GoalsFor': 28,
   'l10Losses': 3,
   'l10OtLosses': 0,
   'l10Points': 14,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 12,
   'leagueL10Sequence': 7,
   'leagueRoadSequence': 3,
   'leagueSequence': 6,
   'losses': 24,
   'otLosses': 10,
   'placeName': {'default': 'Montréal'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.414634,
   'regulationWins': 34,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 129,
   'roadGoalsFor': 146,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Montréal Canadiens',
    'fr': 'Canadiens de Montréal'},
   'teamCommonName': {'default': 'Canadiens'},
   'teamAbbrev': {'default': 'MTL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg',
   'ties': 0,
   'waiversSequence': 27,
   'wildcardSequence': 0,
   'winPctg': 0.585366,
   'wins': 48},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 7,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 4,
   'divisionName': 'Central',
   'divisionRoadSequence': 3,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 240,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 15,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 130,
   'homeLosses': 10,
   'homeOtLosses': 8,
   'homePoints': 54,
   'homeRegulationPlusOtWins': 19,
   'homeRegulationWins': 14,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 32,
   'l10GoalsFor': 36,
   'l10Losses': 4,
   'l10OtLosses': 0,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 7,
   'leagueL10Sequence': 14,
   'leagueRoadSequence': 9,
   'leagueSequence': 7,
   'losses': 24,
   'otLosses': 12,
   'placeName': {'default': 'Minnesota'},
   'pointPctg': 0.634146,
   'points': 104,
   'regulationPlusOtWinPctg': 0.512195,
   'regulationPlusOtWins': 42,
   'regulationWinPctg': 0.378049,
   'regulationWins': 31,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 125,
   'roadGoalsFor': 142,
   'roadLosses': 14,
   'roadOtLosses': 4,
   'roadPoints': 50,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 23,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'},
   'teamCommonName': {'default': 'Wild'},
   'teamAbbrev': {'default': 'MIN'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg',
   'ties': 0,
   'waiversSequence': 26,
   'wildcardSequence': 0,
   'winPctg': 0.560976,
   'wins': 46},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 8,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 13,
   'conferenceSequence': 5,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 4,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 6,
   'divisionSequence': 4,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 22,
   'goalDifferentialPctg': 0.268293,
   'goalAgainst': 250,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 40,
   'homeGoalsAgainst': 105,
   'homeGoalsFor': 145,
   'homeLosses': 11,
   'homeOtLosses': 1,
   'homePoints': 59,
   'homeRegulationPlusOtWins': 28,
   'homeRegulationWins': 23,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 32,
   'l10Losses': 3,
   'l10OtLosses': 2,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 4,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 2,
   'leagueL10Sequence': 16,
   'leagueRoadSequence': 21,
   'leagueSequence': 8,
   'losses': 27,
   'otLosses': 10,
   'placeName': {'default': 'Boston'},
   'pointPctg': 0.609756,
   'points': 100,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.402439,
   'regulationWins': 33,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': -18,
   'roadGoalsAgainst': 145,
   'roadGoalsFor': 127,
   'roadLosses': 16,
   'roadOtLosses': 9,
   'roadPoints': 41,
   'roadRegulationPlusOtWins': 13,
   'roadRegulationWins': 10,
   'roadTies': 0,
   'roadWins': 16,
   'seasonId': 20252026,
   'shootoutLosses': 3,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 2,
   'teamName': {'default': 'Boston Bruins', 'fr': 'Bruins de Boston'},
   'teamCommonName': {'default': 'Bruins'},
   'teamAbbrev': {'default': 'BOS'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg?season=20252026',
   'ties': 0,
   'waiversSequence': 25,
   'wildcardSequence': 1,
   'winPctg': 0.54878,
   'wins': 45},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 6,
   'conferenceL10Sequence': 5,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 7,
   'conferenceSequence': 6,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 4,
   'divisionL10Sequence': 2,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 4,
   'divisionSequence': 5,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 246,
   'goalFor': 278,
   'goalsForPctg': 3.390244,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 31,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 139,
   'homeLosses': 12,
   'homeOtLosses': 6,
   'homePoints': 52,
   'homeRegulationPlusOtWins': 21,
   'homeRegulationWins': 21,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 10,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 36,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 9,
   'leagueL10Sequence': 10,
   'leagueRoadSequence': 11,
   'leagueSequence': 9,
   'losses': 27,
   'otLosses': 11,
   'placeName': {'default': 'Ottawa'},
   'pointPctg': 0.603659,
   'points': 99,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 1,
   'roadGoalsAgainst': 138,
   'roadGoalsFor': 139,
   'roadLosses': 15,
   'roadOtLosses': 5,
   'roadPoints': 47,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 17,

In [5]:
data['standings'][0]

{'clinchIndicator': 'p',
 'conferenceAbbrev': 'W',
 'conferenceHomeSequence': 1,
 'conferenceL10Sequence': 2,
 'conferenceName': 'Western',
 'conferenceRoadSequence': 1,
 'conferenceSequence': 1,
 'date': '2026-04-17',
 'divisionAbbrev': 'C',
 'divisionHomeSequence': 1,
 'divisionL10Sequence': 1,
 'divisionName': 'Central',
 'divisionRoadSequence': 1,
 'divisionSequence': 1,
 'gameTypeId': 2,
 'gamesPlayed': 82,
 'goalDifferential': 99,
 'goalDifferentialPctg': 1.207317,
 'goalAgainst': 203,
 'goalFor': 302,
 'goalsForPctg': 3.682927,
 'homeGamesPlayed': 41,
 'homeGoalDifferential': 49,
 'homeGoalsAgainst': 108,
 'homeGoalsFor': 157,
 'homeLosses': 9,
 'homeOtLosses': 6,
 'homePoints': 58,
 'homeRegulationPlusOtWins': 25,
 'homeRegulationWins': 25,
 'homeTies': 0,
 'homeWins': 26,
 'l10GamesPlayed': 10,
 'l10GoalDifferential': 14,
 'l10GoalsAgainst': 20,
 'l10GoalsFor': 34,
 'l10Losses': 2,
 'l10OtLosses': 1,
 'l10Points': 15,
 'l10RegulationPlusOtWins': 6,
 'l10RegulationWins': 6,
 'l10Ties': 0,
 'l10Wins': 7,
 'leagueHomeSequence': 3,
 'leagueL10Sequence': 4,
 'leagueRoadSequence': 1,
 'leagueSequence': 1,
 'losses': 16,
 'otLosses': 11,
 'placeName': {'default': 'Colorado'},
 'pointPctg': 0.737805,
 'points': 121,
 'regulationPlusOtWinPctg': 0.621951,
 'regulationPlusOtWins': 51,
 'regulationWinPctg': 0.585366,
 'regulationWins': 48,
 'roadGamesPlayed': 41,
 'roadGoalDifferential': 50,
 'roadGoalsAgainst': 95,
 'roadGoalsFor': 145,
 'roadLosses': 7,
 'roadOtLosses': 5,
 'roadPoints': 63,
 'roadRegulationPlusOtWins': 26,
 'roadRegulationWins': 23,
 'roadTies': 0,
 'roadWins': 29,
 'seasonId': 20252026,
 'shootoutLosses': 6,
 'shootoutWins': 4,
 'streakCode': 'W',
 'streakCount': 3,
 'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'},
 'teamCommonName': {'default': 'Avalanche'},
 'teamAbbrev': {'default': 'COL'},
 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
 'ties': 0,
 'waiversSequence': 32,
 'wildcardSequence': 0,
 'winPctg': 0.670732,
 'wins': 55}

In [3]:

games_played = data['standings'][0]['gamesPlayed']
wins = data['standings'][0]['wins']
losses = data['standings'][0]['losses']
ot_losses = data['standings'][0]['otLosses']
points = data['standings'][0]['points']
goals_for = data['standings'][0]['goalFor']
goals_against = data['standings'][0]['goalAgainst']
home_wins = data['standings'][0]['homeWins']
away_wins = data['standings'][0]['roadWins']
streak_type = data['standings'][0]['streakCode']
streak_count = data['standings'][0]['streakCount']

In [5]:
records = []

season = "20252026"

for team in data['standings']:
    records.append({
        'season': season,
        'games_played': team['gamesPlayed'],
        'wins': team['wins'],
        'losses': team['losses'],
        'ot_losses': team['otLosses'],
        'points': team['points'],
        'goals_for': team['goalFor'],
        'goals_against': team['goalAgainst'],
        'home_wins': team['homeWins'],
        'away_wins': team['roadWins'],
        'streak_type': team['streakCode'],
        'streak_count': team['streakCount']
    })

In [2]:
import pymysql
conn=pymysql.connect(host='localhost',
                     user='root',
                     password='13849#Datasci',
                     database='proj1'
                     )
cursor=conn.cursor()

In [18]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS standings (
    standing_id INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT AUTO_INCREMENT PRIMARY KEY,
    season VARCHAR(20),
    games_played INT,
    wins INT,
    losses INT,
    ot_losses INT,
    points INT,
    goals_for INT,
    goals_against INT,
    home_wins INT,
    away_wins INT,
    streak_type VARCHAR(20),
    streak_count INT,
    FOREIGN KEY (team_id) REFERENCES teams(team_id)
)
""")

conn.commit()

In [34]:
INSERT_QUERY = """
INSERT INTO standings
(
    team_id,
    season,
    games_played,
    wins,
    losses,
    ot_losses,
    points,
    goals_for,
    goals_against,
    home_wins,
    away_wins,
    streak_type,
    streak_count
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [35]:
for i in records:
    
    values = (
        i['team_id'],
        i['season'],
        i['games_played'],
        i['wins'],
        i['losses'],
        i['ot_losses'],
        i['points'],
        i['goals_for'],
        i['goals_against'],
        i['home_wins'],
        i['away_wins'],
        i['streak_type'],
        i['streak_count']
    )

    cursor.execute(INSERT_QUERY, values)

conn.commit()

In [36]:
cursor.execute("SELECT * FROM standings")
rows = cursor.fetchall()
for row in rows:
    print(row)

(1, 3, '20252026', 82, 55, 16, 11, 121, 302, 203, 26, 29, 'W', 3)
(2, 4, '20252026', 82, 53, 22, 7, 113, 296, 240, 29, 24, 'W', 1)
(3, 5, '20252026', 82, 50, 20, 12, 112, 279, 226, 26, 24, 'W', 5)
(4, 6, '20252026', 82, 50, 23, 9, 109, 288, 241, 26, 24, 'OT', 1)
(5, 7, '20252026', 82, 50, 26, 6, 106, 290, 231, 26, 24, 'L', 1)
(6, 8, '20252026', 82, 48, 24, 10, 106, 283, 256, 24, 24, 'L', 1)
(7, 9, '20252026', 82, 46, 24, 12, 104, 272, 240, 23, 23, 'W', 1)
(8, 10, '20252026', 82, 45, 27, 10, 100, 272, 250, 29, 16, 'W', 2)
(9, 11, '20252026', 82, 44, 27, 11, 99, 278, 246, 23, 21, 'W', 1)
(10, 12, '20252026', 82, 41, 25, 16, 98, 293, 268, 20, 21, 'L', 3)
(11, 13, '20252026', 82, 43, 27, 12, 98, 250, 243, 20, 23, 'W', 3)
(12, 14, '20252026', 82, 43, 30, 9, 95, 263, 244, 25, 18, 'W', 4)
(13, 15, '20252026', 82, 39, 26, 17, 95, 265, 250, 20, 19, 'W', 3)
(14, 16, '20252026', 82, 41, 30, 11, 93, 282, 269, 22, 19, 'W', 1)
(15, 17, '20252026', 82, 43, 33, 6, 92, 268, 240, 22, 21, 'L', 1)
(16, 18, '20252026', 82, 41, 31, 10, 92, 241, 258, 21, 20, 'L', 1)
(17, 19, '20252026', 82, 40, 30, 12, 92, 253, 253, 20, 20, 'L', 2)
(18, 20, '20252026', 82, 43, 33, 6, 92, 273, 288, 24, 19, 'W', 1)
(19, 21, '20252026', 82, 43, 34, 5, 91, 233, 241, 22, 21, 'L', 3)
(20, 22, '20252026', 82, 35, 27, 20, 90, 225, 247, 15, 20, 'L', 1)
(21, 23, '20252026', 82, 42, 37, 3, 87, 230, 254, 21, 21, 'L', 1)
(22, 24, '20252026', 82, 37, 33, 12, 86, 231, 258, 20, 17, 'W', 4)
(23, 25, '20252026', 82, 38, 34, 10, 86, 247, 269, 21, 17, 'L', 2)
(24, 26, '20252026', 82, 39, 35, 8, 86, 251, 292, 21, 18, 'W', 1)
(25, 27, '20252026', 82, 40, 38, 4, 84, 251, 276, 23, 17, 'W', 3)
(26, 28, '20252026', 82, 35, 35, 12, 82, 231, 260, 19, 16, 'L', 4)
(27, 29, '20252026', 82, 34, 37, 11, 79, 226, 263, 19, 15, 'L', 3)
(28, 30, '20252026', 82, 32, 36, 14, 78, 253, 299, 18, 14, 'L', 5)
(29, 31, '20252026', 82, 34, 39, 9, 77, 212, 259, 23, 11, 'W', 1)
(30, 32, '20252026', 82, 34, 39, 9, 77, 238, 250, 14, 20, 'W', 1)
(31, 33, '20252026', 82, 29, 39, 14, 72, 213, 275, 14, 15, 'W', 1)
(32, 34, '20252026', 82, 25, 49, 8, 58, 216, 316, 9, 16, 'L', 1)

In [37]:
print(data['standings'][0].keys())

dict_keys(['clinchIndicator', 'conferenceAbbrev', 'conferenceHomeSequence', 'conferenceL10Sequence', 'conferenceName', 'conferenceRoadSequence', 'conferenceSequence', 'date', 'divisionAbbrev', 'divisionHomeSequence', 'divisionL10Sequence', 'divisionName', 'divisionRoadSequence', 'divisionSequence', 'gameTypeId', 'gamesPlayed', 'goalDifferential', 'goalDifferentialPctg', 'goalAgainst', 'goalFor', 'goalsForPctg', 'homeGamesPlayed', 'homeGoalDifferential', 'homeGoalsAgainst', 'homeGoalsFor', 'homeLosses', 'homeOtLosses', 'homePoints', 'homeRegulationPlusOtWins', 'homeRegulationWins', 'homeTies', 'homeWins', 'l10GamesPlayed', 'l10GoalDifferential', 'l10GoalsAgainst', 'l10GoalsFor', 'l10Losses', 'l10OtLosses', 'l10Points', 'l10RegulationPlusOtWins', 'l10RegulationWins', 'l10Ties', 'l10Wins', 'leagueHomeSequence', 'leagueL10Sequence', 'leagueRoadSequence', 'leagueSequence', 'losses', 'otLosses', 'placeName', 'pointPctg', 'points', 'regulationPlusOtWinPctg', 'regulationPlusOtWins', 'regulationWinPctg', 'regulationWins', 'roadGamesPlayed', 'roadGoalDifferential', 'roadGoalsAgainst', 'roadGoalsFor', 'roadLosses', 'roadOtLosses', 'roadPoints', 'roadRegulationPlusOtWins', 'roadRegulationWins', 'roadTies', 'roadWins', 'seasonId', 'shootoutLosses', 'shootoutWins', 'streakCode', 'streakCount', 'teamName', 'teamCommonName', 'teamAbbrev', 'teamLogo', 'teamLogoDark', 'ties', 'waiversSequence', 'wildcardSequence', 'winPctg', 'wins'])

In [38]:
import pandas as pd
df=pd.read_sql_query("select * from standings",conn)
df

C:\Users\dines\AppData\Local\Temp\ipykernel_25116\2434006533.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("select * from standings",conn)

,standing_id,team_id,season,games_played,wins,losses,ot_losses,points,goals_for,goals_against,home_wins,away_wins,streak_type,streak_count
0,1,3,20252026,82,55,16,11,121,302,203,26,29,W,3
1,2,4,20252026,82,53,22,7,113,296,240,29,24,W,1
2,3,5,20252026,82,50,20,12,112,279,226,26,24,W,5
3,4,6,20252026,82,50,23,9,109,288,241,26,24,OT,1
4,5,7,20252026,82,50,26,6,106,290,231,26,24,L,1
5,6,8,20252026,82,48,24,10,106,283,256,24,24,L,1
6,7,9,20252026,82,46,24,12,104,272,240,23,23,W,1
7,8,10,20252026,82,45,27,10,100,272,250,29,16,W,2
8,9,11,20252026,82,44,27,11,99,278,246,23,21,W,1
9,10,12,20252026,82,41,25,16,98,293,268,20,21,L,3
10,11,13,20252026,82,43,27,12,98,250,243,20,23,W,3
11,12,14,20252026,82,43,30,9,95,263,244,25,18,W,4
12,13,15,20252026,82,39,26,17,95,265,250,20,19,W,3
13,14,16,20252026,82,41,30,11,93,282,269,22,19,W,1
14,15,17,20252026,82,43,33,6,92,268,240,22,21,L,1
15,16,18,20252026,82,41,31,10,92,241,258,21,20,L,1
16,17,19,20252026,82,40,30,12,92,253,253,20,20,L,2
17,18,20,20252026,82,43,33,6,92,273,288,24,19,W,1
18,19,21,20252026,82,43,34,5,91,233,241,22,21,L,3
19,20,22,20252026,82,35,27,20,90,225,247,15,20,L,1
20,21,23,20252026,82,42,37,3,87,230,254,21,21,L,1
21,22,24,20252026,82,37,33,12,86,231,258,20,17,W,4
22,23,25,20252026,82,38,34,10,86,247,269,21,17,L,2
23,24,26,20252026,82,39,35,8,86,251,292,21,18,W,1
24,25,27,20252026,82,40,38,4,84,251,276,23,17,W,3
25,26,28,20252026,82,35,35,12,82,231,260,19,16,L,4
26,27,29,20252026,82,34,37,11,79,226,263,19,15,L,3
27,28,30,20252026,82,32,36,14,78,253,299,18,14,L,5
28,29,31,20252026,82,34,39,9,77,212,259,23,11,W,1
29,30,32,20252026,82,34,39,9,77,238,250,14,20,W,1
30,31,33,20252026,82,29,39,14,72,213,275,14,15,W,1
31,32,34,20252026,82,25,49,8,58,216,316,9,16,L,1

In [ ]:
#TABLE 3 : PLAYERS

200
dict_keys(['forwards', 'defensemen', 'goalies'])

In [1]:
import pymysql

conn = pymysql.connect(
    host="localhost",
    user="root",
    password="13849#Datasci",
    database="proj1"
)

cursor = conn.cursor()

In [17]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS players (
    player_id BIGINT PRIMARY KEY,
    team_id INT,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    position VARCHAR(10),
    jersey_number INT,
    birth_date DATE,
    birth_country VARCHAR(10),
    height_cm REAL,
    weight_kg REAL,
    shoots_catches VARCHAR(5),
    headshot_url TEXT,
    FOREIGN KEY (team_id) REFERENCES teams(team_id)

)
""")

conn.commit()

In [46]:
cursor.execute("""
SELECT team_id, team_abbrev
FROM teams
""")

teams = cursor.fetchall()

In [45]:

team_lookup = { team_abbrev: team_id
    for team_id, team_abbrev in cursor.fetchall()
}

In [94]:
import requests
for team_abbrev, team_id in team_lookup.items(): 
    url = f"https://api-web.nhle.com/v1/roster/{team_abbrev}/current"
    response = requests.get(url)
    print("Team:", team_abbrev)
    for group in ("forwards", "defensemen", "goalies"):
        for player in data.get(group, []):
            values = (
                player['id'],
                team_id,
                player['firstName']['default'],
                player['lastName']['default'],
                player.get('positionCode'),
                player.get('sweaterNumber'),
                player.get('birthDate'),
                player.get('birthCountry'),
                player.get('heightInCentimeters'),
                player.get('weightInKilograms'),
                player.get('shootsCatches'),
                player.get('headshot')
            )

            print(values)

Team: ANA
(8483804, 20, 'Riley', 'Bezeau', 'R', None, '2002-05-04', 'USA', 183, 85, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483804.png')
(8475745, 20, 'Charlie', 'Coyle', 'C', 3, '1992-03-02', 'USA', 191, 100, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8475745.png')
(8483432, 20, 'Luca', 'Del Bel Belluz', 'C', 93, '2003-11-10', 'CAN', 185, 84, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483432.png')
(8483688, 20, 'Jordan', 'Dumais', 'R', 22, '2004-04-15', 'CAN', 173, 78, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483688.png')
(8486173, 20, 'Josh', 'Eernisse', 'C', None, '2001-12-31', 'USA', 191, 98, None, 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8486173.png')
(8478856, 20, 'Conor', 'Garland', 'R', 83, '1996-03-11', 'USA', 178, 75, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478856.png')
(8478046, 20, 'Danton', 'Heinen', 'L', 43, '1995-07-05', 'CAN', 188, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478046.png')
(8482660, 20, 'Kent', 'Johnson', 'C', 91, '2002-10-18', 'CAN', 183, 77, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482660.png')
(8484472, 20, 'Oiva', 'Keskinen', 'C', 20, '2004-02-28', 'FIN', 183, 82, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484472.png')
(8479066, 20, 'Ryan', 'Lomberg', 'L', 94, '1994-12-09', 'CAN', 175, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479066.png')
(8480806, 20, 'Isac', 'Lundeström', 'C', 21, '1999-11-06', 'SWE', 185, 87, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480806.png')
(8482744, 20, 'James', 'Malatesta', 'L', 67, '2003-05-31', 'CAN', 175, 88, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482744.png')
(8480893, 20, 'Kirill', 'Marchenko', 'R', 86, '2000-07-21', 'RUS', 191, 91, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480893.png')
(8482881, 20, 'Max', 'McCue', 'C', 93, '2003-02-10', 'CAN', 185, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482881.png')
(8477497, 20, 'Sean', 'Monahan', 'C', 23, '1994-10-12', 'CAN', 188, 93, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477497.png')
(8477501, 20, 'Valeri', 'Nichushkin', 'R', 43, '1995-03-04', 'RUS', 193, 95, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477501.png')
(8479671, 20, 'Mathieu', 'Olivier', 'R', 24, '1997-02-11', 'USA', 185, 105, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479671.png')
(8484214, 20, 'Luca', 'Pinelli', 'C', 53, '2005-04-05', 'CAN', 175, 80, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484214.png')
(8482705, 20, 'Cole', 'Sillinger', 'C', 4, '2003-05-16', 'USA', 183, 92, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482705.png')
(8483538, 20, 'Owen', 'Sillinger', 'C', 12, '1997-09-23', 'CAN', 178, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483538.png')
(8482134, 20, 'Luke', 'Tuch', 'L', None, '2002-03-07', 'USA', 191, 98, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482134.png')
(8481716, 20, 'Dmitri', 'Voronkov', 'L', 10, '2000-09-10', 'RUS', 196, 106, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8481716.png')
(8485469, 20, 'Jack', 'Williams', 'R', 92, '2002-03-02', 'USA', 180, 84, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8485469.png')
(8477425, 20, 'Miles', 'Wood', 'L', 11, '1995-09-13', 'USA', 188, 95, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477425.png')
(8486177, 20, 'Boston', 'Buckberger', 'D', None, '2003-06-01', 'CAN', 183, 86, None, 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8486177.png')
(8482678, 20, 'Corson', 'Ceulemans', 'D', 74, '2003-05-05', 'CAN', 188, 90, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482678.png')
(8481161, 20, 'Jake', 'Christiansen', 'D', 2, '1999-09-12', 'CAN', 183, 90, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8481161.png')
(8484808, 20, 'Charlie', 'Elick', 'D', 57, '2006-01-17', 'CAN', 191, 88, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484808.png')
(8479371, 20, 'Dante', 'Fabbro', 'D', 15, '1998-06-20', 'CAN', 183, 91, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479371.png')
(8475790, 20, 'Erik', 'Gudbranson', 'D', 44, '1992-01-07', 'CAN', 196, 101, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8475790.png')
(8485472, 20, 'Caleb', 'MacDonald', 'D', 95, '2002-11-29', 'CAN', 193, 102, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8485472.png')
(8484777, 20, 'Luca', 'Marrelli', 'D', 54, '2005-10-04', 'CAN', 185, 82, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484777.png')
(8483485, 20, 'Denton', 'Mateychuk', 'D', 5, '2004-07-12', 'CAN', 180, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483485.png')
(8478500, 20, 'Ivan', 'Provorov', 'D', 9, '1997-01-13', 'RUS', 185, 102, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478500.png')
(8482692, 20, 'Guillaume', 'Richard', 'D', 84, '2003-02-10', 'CAN', 188, 77, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482692.png')
(8476923, 20, 'Damon', 'Severson', 'D', 78, '1994-08-07', 'CAN', 188, 93, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8476923.png')
(8478460, 20, 'Zach', 'Werenski', 'D', 8, '1997-07-19', 'USA', 188, 97, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478460.png')
(8478841, 20, 'Colton', 'White', 'D', None, '1997-05-03', 'CAN', 185, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478841.png')
(8477831, 20, 'Pheonix', 'Copley', 'G', 29, '1992-01-18', 'USA', 193, 93, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477831.png')
(8484997, 20, 'Evan', 'Gardner', 'G', 35, '2006-01-25', 'CAN', 183, 79, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484997.png')
(8482982, 20, 'Jet', 'Greaves', 'G', 73, '2001-03-30', 'CAN', 183, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482982.png')
(8483869, 20, 'Nolan', 'Lalonde', 'G', 31, '2004-02-14', 'CAN', 185, 86, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483869.png')
(8478007, 20, 'Elvis', 'Merzlikins', 'G', 90, '1994-04-13', 'LVA', 191, 86, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478007.png')
Team: BOS
(8483804, 10, 'Riley', 'Bezeau', 'R', None, '2002-05-04', 'USA', 183, 85, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483804.png')
(8475745, 10, 'Charlie', 'Coyle', 'C', 3, '1992-03-02', 'USA', 191, 100, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8475745.png')
(8483432, 10, 'Luca', 'Del Bel Belluz', 'C', 93, '2003-11-10', 'CAN', 185, 84, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483432.png')
(8483688, 10, 'Jordan', 'Dumais', 'R', 22, '2004-04-15', 'CAN', 173, 78, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483688.png')
(8486173, 10, 'Josh', 'Eernisse', 'C', None, '2001-12-31', 'USA', 191, 98, None, 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8486173.png')
(8478856, 10, 'Conor', 'Garland', 'R', 83, '1996-03-11', 'USA', 178, 75, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478856.png')
(8478046, 10, 'Danton', 'Heinen', 'L', 43, '1995-07-05', 'CAN', 188, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478046.png')
(8482660, 10, 'Kent', 'Johnson', 'C', 91, '2002-10-18', 'CAN', 183, 77, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482660.png')
(8484472, 10, 'Oiva', 'Keskinen', 'C', 20, '2004-02-28', 'FIN', 183, 82, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484472.png')
(8479066, 10, 'Ryan', 'Lomberg', 'L', 94, '1994-12-09', 'CAN', 175, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479066.png')
(8480806, 10, 'Isac', 'Lundeström', 'C', 21, '1999-11-06', 'SWE', 185, 87, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480806.png')
(8482744, 10, 'James', 'Malatesta', 'L', 67, '2003-05-31', 'CAN', 175, 88, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482744.png')
(8480893, 10, 'Kirill', 'Marchenko', 'R', 86, '2000-07-21', 'RUS', 191, 91, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480893.png')
(8482881, 10, 'Max', 'McCue', 'C', 93, '2003-02-10', 'CAN', 185, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482881.png')
(8477497, 10, 'Sean', 'Monahan', 'C', 23, '1994-10-12', 'CAN', 188, 93, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477497.png')
(8477501, 10, 'Valeri', 'Nichushkin', 'R', 43, '1995-03-04', 'RUS', 193, 95, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477501.png')
(8479671, 10, 'Mathieu', 'Olivier', 'R', 24, '1997-02-11', 'USA', 185, 105, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479671.png')
(8484214, 10, 'Luca', 'Pinelli', 'C', 53, '2005-04-05', 'CAN', 175, 80, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484214.png')
(8482705, 10, 'Cole', 'Sillinger', 'C', 4, '2003-05-16', 'USA', 183, 92, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482705.png')
(8483538, 10, 'Owen', 'Sillinger', 'C', 12, '1997-09-23', 'CAN', 178, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483538.png')
(8482134, 10, 'Luke', 'Tuch', 'L', None, '2002-03-07', 'USA', 191, 98, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482134.png')
(8481716, 10, 'Dmitri', 'Voronkov', 'L', 10, '2000-09-10', 'RUS', 196, 106, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8481716.png')
(8485469, 10, 'Jack', 'Williams', 'R', 92, '2002-03-02', 'USA', 180, 84, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8485469.png')
(8477425, 10, 'Miles', 'Wood', 'L', 11, '1995-09-13', 'USA', 188, 95, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477425.png')
(8486177, 10, 'Boston', 'Buckberger', 'D', None, '2003-06-01', 'CAN', 183, 86, None, 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8486177.png')
(8482678, 10, 'Corson', 'Ceulemans', 'D', 74, '2003-05-05', 'CAN', 188, 90, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482678.png')
(8481161, 10, 'Jake', 'Christiansen', 'D', 2, '1999-09-12', 'CAN', 183, 90, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8481161.png')
(8484808, 10, 'Charlie', 'Elick', 'D', 57, '2006-01-17', 'CAN', 191, 88, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484808.png')
(8479371, 10, 'Dante', 'Fabbro', 'D', 15, '1998-06-20', 'CAN', 183, 91, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479371.png')
(8475790, 10, 'Erik', 'Gudbranson', 'D', 44, '1992-01-07', 'CAN', 196, 101, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8475790.png')
(8485472, 10, 'Caleb', 'MacDonald', 'D', 95, '2002-11-29', 'CAN', 193, 102, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8485472.png')
(8484777, 10, 'Luca', 'Marrelli', 'D', 54, '2005-10-04', 'CAN', 185, 82, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484777.png')
(8483485, 10, 'Denton', 'Mateychuk', 'D', 5, '2004-07-12', 'CAN', 180, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483485.png')
(8478500, 10, 'Ivan', 'Provorov', 'D', 9, '1997-01-13', 'RUS', 185, 102, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478500.png')
(8482692, 10, 'Guillaume', 'Richard', 'D', 84, '2003-02-10', 'CAN', 188, 77, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482692.png')
(8476923, 10, 'Damon', 'Severson', 'D', 78, '1994-08-07', 'CAN', 188, 93, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8476923.png')
(8478460, 10, 'Zach', 'Werenski', 'D', 8, '1997-07-19', 'USA', 188, 97, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478460.png')
(8478841, 10, 'Colton', 'White', 'D', None, '1997-05-03', 'CAN', 185, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478841.png')
(8477831, 10, 'Pheonix', 'Copley', 'G', 29, '1992-01-18', 'USA', 193, 93, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477831.png')
(8484997, 10, 'Evan', 'Gardner', 'G', 35, '2006-01-25', 'CAN', 183, 79, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484997.png')
(8482982, 10, 'Jet', 'Greaves', 'G', 73, '2001-03-30', 'CAN', 183, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482982.png')
(8483869, 10, 'Nolan', 'Lalonde', 'G', 31, '2004-02-14', 'CAN', 185, 86, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483869.png')
(8478007, 10, 'Elvis', 'Merzlikins', 'G', 90, '1994-04-13', 'LVA', 191, 86, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478007.png')
Team: BUF
(8483804, 6, 'Riley', 'Bezeau', 'R', None, '2002-05-04', 'USA', 183, 85, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483804.png')
(8475745, 6, 'Charlie', 'Coyle', 'C', 3, '1992-03-02', 'USA', 191, 100, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8475745.png')
(8483432, 6, 'Luca', 'Del Bel Belluz', 'C', 93, '2003-11-10', 'CAN', 185, 84, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483432.png')
(8483688, 6, 'Jordan', 'Dumais', 'R', 22, '2004-04-15', 'CAN', 173, 78, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483688.png')
(8486173, 6, 'Josh', 'Eernisse', 'C', None, '2001-12-31', 'USA', 191, 98, None, 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8486173.png')
(8478856, 6, 'Conor', 'Garland', 'R', 83, '1996-03-11', 'USA', 178, 75, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478856.png')
(8478046, 6, 'Danton', 'Heinen', 'L', 43, '1995-07-05', 'CAN', 188, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478046.png')
(8482660, 6, 'Kent', 'Johnson', 'C', 91, '2002-10-18', 'CAN', 183, 77, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482660.png')
(8484472, 6, 'Oiva', 'Keskinen', 'C', 20, '2004-02-28', 'FIN', 183, 82, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484472.png')
(8479066, 6, 'Ryan', 'Lomberg', 'L', 94, '1994-12-09', 'CAN', 175, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479066.png')
(8480806, 6, 'Isac', 'Lundeström', 'C', 21, '1999-11-06', 'SWE', 185, 87, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480806.png')
(8482744, 6, 'James', 'Malatesta', 'L', 67, '2003-05-31', 'CAN', 175, 88, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482744.png')
(8480893, 6, 'Kirill', 'Marchenko', 'R', 86, '2000-07-21', 'RUS', 191, 91, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480893.png')
(8482881, 6, 'Max', 'McCue', 'C', 93, '2003-02-10', 'CAN', 185, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482881.png')
(8477497, 6, 'Sean', 'Monahan', 'C', 23, '1994-10-12', 'CAN', 188, 93, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477497.png')
(8477501, 6, 'Valeri', 'Nichushkin', 'R', 43, '1995-03-04', 'RUS', 193, 95, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477501.png')
(8479671, 6, 'Mathieu', 'Olivier', 'R', 24, '1997-02-11', 'USA', 185, 105, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479671.png')
(8484214, 6, 'Luca', 'Pinelli', 'C', 53, '2005-04-05', 'CAN', 175, 80, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484214.png')
(8482705, 6, 'Cole', 'Sillinger', 'C', 4, '2003-05-16', 'USA', 183, 92, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482705.png')
(8483538, 6, 'Owen', 'Sillinger', 'C', 12, '1997-09-23', 'CAN', 178, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483538.png')
(8482134, 6, 'Luke', 'Tuch', 'L', None, '2002-03-07', 'USA', 191, 98, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482134.png')
(8481716, 6, 'Dmitri', 'Voronkov', 'L', 10, '2000-09-10', 'RUS', 196, 106, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8481716.png')
(8485469, 6, 'Jack', 'Williams', 'R', 92, '2002-03-02', 'USA', 180, 84, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8485469.png')
(8477425, 6, 'Miles', 'Wood', 'L', 11, '1995-09-13', 'USA', 188, 95, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477425.png')
(8486177, 6, 'Boston', 'Buckberger', 'D', None, '2003-06-01', 'CAN', 183, 86, None, 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8486177.png')
(8482678, 6, 'Corson', 'Ceulemans', 'D', 74, '2003-05-05', 'CAN', 188, 90, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482678.png')
(8481161, 6, 'Jake', 'Christiansen', 'D', 2, '1999-09-12', 'CAN', 183, 90, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8481161.png')
(8484808, 6, 'Charlie', 'Elick', 'D', 57, '2006-01-17', 'CAN', 191, 88, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484808.png')
(8479371, 6, 'Dante', 'Fabbro', 'D', 15, '1998-06-20', 'CAN', 183, 91, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479371.png')
(8475790, 6, 'Erik', 'Gudbranson', 'D', 44, '1992-01-07', 'CAN', 196, 101, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8475790.png')
(8485472, 6, 'Caleb', 'MacDonald', 'D', 95, '2002-11-29', 'CAN', 193, 102, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8485472.png')
(8484777, 6, 'Luca', 'Marrelli', 'D', 54, '2005-10-04', 'CAN', 185, 82, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484777.png')
(8483485, 6, 'Denton', 'Mateychuk', 'D', 5, '2004-07-12', 'CAN', 180, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483485.png')
(8478500, 6, 'Ivan', 'Provorov', 'D', 9, '1997-01-13', 'RUS', 185, 102, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478500.png')
(8482692, 6, 'Guillaume', 'Richard', 'D', 84, '2003-02-10', 'CAN', 188, 77, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482692.png')
(8476923, 6, 'Damon', 'Severson', 'D', 78, '1994-08-07', 'CAN', 188, 93, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8476923.png')
(8478460, 6, 'Zach', 'Werenski', 'D', 8, '1997-07-19', 'USA', 188, 97, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478460.png')
(8478841, 6, 'Colton', 'White', 'D', None, '1997-05-03', 'CAN', 185, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478841.png')
(8477831, 6, 'Pheonix', 'Copley', 'G', 29, '1992-01-18', 'USA', 193, 93, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8477831.png')
(8484997, 6, 'Evan', 'Gardner', 'G', 35, '2006-01-25', 'CAN', 183, 79, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484997.png')
(8482982, 6, 'Jet', 'Greaves', 'G', 73, '2001-03-30', 'CAN', 183, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482982.png')
(8483869, 6, 'Nolan', 'Lalonde', 'G', 31, '2004-02-14', 'CAN', 185, 86, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483869.png')
(8478007, 6, 'Elvis', 'Merzlikins', 'G', 90, '1994-04-13', 'LVA', 191, 86, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478007.png')
Team: CAR
(8483804, 4, 'Riley', 'Bezeau', 'R', None, '2002-05-04', 'USA', 183, 85, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483804.png')
(8475745, 4, 'Charlie', 'Coyle', 'C', 3, '1992-03-02', 'USA', 191, 100, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8475745.png')
(8483432, 4, 'Luca', 'Del Bel Belluz', 'C', 93, '2003-11-10', 'CAN', 185, 84, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483432.png')
(8483688, 4, 'Jordan', 'Dumais', 'R', 22, '2004-04-15', 'CAN', 173, 78, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8483688.png')
(8486173, 4, 'Josh', 'Eernisse', 'C', None, '2001-12-31', 'USA', 191, 98, None, 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8486173.png')
(8478856, 4, 'Conor', 'Garland', 'R', 83, '1996-03-11', 'USA', 178, 75, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478856.png')
(8478046, 4, 'Danton', 'Heinen', 'L', 43, '1995-07-05', 'CAN', 188, 85, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8478046.png')
(8482660, 4, 'Kent', 'Johnson', 'C', 91, '2002-10-18', 'CAN', 183, 77, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482660.png')
(8484472, 4, 'Oiva', 'Keskinen', 'C', 20, '2004-02-28', 'FIN', 183, 82, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8484472.png')
(8479066, 4, 'Ryan', 'Lomberg', 'L', 94, '1994-12-09', 'CAN', 175, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8479066.png')
(8480806, 4, 'Isac', 'Lundeström', 'C', 21, '1999-11-06', 'SWE', 185, 87, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480806.png')
(8482744, 4, 'James', 'Malatesta', 'L', 67, '2003-05-31', 'CAN', 175, 88, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482744.png')
(8480893, 4, 'Kirill', 'Marchenko', 'R', 86, '2000-07-21', 'RUS', 191, 91, 'R', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8480893.png')
(8482881, 4, 'Max', 'McCue', 'C', 93, '2003-02-10', 'CAN', 185, 83, 'L', 'https://assets.nhle.com/mugs/nhl/20262027/CBJ/8482881.png')

In [160]:

INSERT_QUERY = """
INSERT INTO players
(
    player_id,
    team_id,
    first_name,
    last_name,
    position,
    jersey_number,
    birth_date,
    birth_country,
    height_cm,
    weight_kg,
    shoots_catches,
    headshot_url
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [3]:
conn.commit()
cursor.execute("SELECT * FROM players")
records = cursor.fetchall()

NameError: name 'conn' is not defined

In [4]:
import pandas as pd

In [163]:
df=pd.read_sql_query("select * from players",conn)
df

C:\Users\dines\AppData\Local\Temp\ipykernel_17228\2669807433.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("select * from players",conn)

,player_id,team_id,first_name,last_name,position,jersey_number,birth_date,birth_country,height_cm,weight_kg,shoots_catches,headshot_url
0,8473533,4,Jordan,Staal,C,11.0,1988-09-10,CAN,193.0,100.0,L,https://assets.nhle.com/mugs/nhl/20262027/CAR/...
1,8473986,20,Alex,Killorn,L,17.0,1989-09-14,CAN,185.0,93.0,L,https://assets.nhle.com/mugs/nhl/20262027/ANA/...
2,8475184,20,Chris,Kreider,L,20.0,1991-04-30,USA,191.0,105.0,L,https://assets.nhle.com/mugs/nhl/20262027/ANA/...
3,8475235,4,Nicolas,Deslauriers,L,44.0,1991-02-22,CAN,185.0,99.0,L,https://assets.nhle.com/mugs/nhl/20262027/CAR/...
4,8475324,20,Nick,Jensen,D,4.0,1990-09-21,USA,183.0,92.0,R,https://assets.nhle.com/mugs/nhl/20262027/ANA/...
...,...,...,...,...,...,...,...,...,...,...,...,...
207,8486052,20,Nikita,Klepov,R,40.0,2008-06-27,USA,183.0,82.0,L,https://assets.nhle.com/mugs/nhl/20262027/ANA/...
208,8486072,20,Marcus,Nordmark,L,43.0,2008-05-04,SWE,188.0,82.0,L,https://assets.nhle.com/mugs/nhl/20262027/ANA/...
209,8486148,10,Max,Lundgren,G,80.0,2002-04-03,SWE,196.0,104.0,L,https://assets.nhle.com/mugs/nhl/20262027/BOS/...
210,8486173,19,Josh,Eernisse,C,NaN,2001-12-31,USA,191.0,98.0,NaN,https://assets.nhle.com/mugs/nhl/20262027/CBJ/...
211,8486177,19,Boston,Buckberger,D,NaN,2003-06-01,CAN,183.0,86.0,NaN,https://assets.nhle.com/mugs/nhl/20262027/CBJ/...

 TABLE 4 : GAMES

In [13]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS games (
    game_id BIGINT PRIMARY KEY,
    season VARCHAR(20),
    game_type INT,
    game_date DATE,
    home_team_id INT,
    away_team_id INT,
    home_score INT,
    away_score INT,
    game_state VARCHAR(20),
    venue_name VARCHAR(150),

    FOREIGN KEY (home_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (away_team_id) REFERENCES teams(team_id)
)
""")
conn.commit()

In [14]:
cursor.execute("SELECT team_id, team_abbrev FROM teams")
teams = cursor.fetchall()

In [15]:
team_lookup = {}
for team_id, team_abbrev in teams:
    team_lookup[team_abbrev] = team_id

In [16]:
team_lookup

{'ANA': 20,
 'BOS': 10,
 'BUF': 6,
 'CAR': 4,
 'CBJ': 19,
 'Central': 1,
 'CGY': 31,
 'CHI': 33,
 'COL': 3,
 'DAL': 5,
 'DET': 18,
 'EDM': 16,
 'FLA': 27,
 'LAK': 22,
 'MIN': 9,
 'MTL': 8,
 'NJD': 23,
 'NSH': 25,
 'NYI': 21,
 'NYR': 32,
 'OTT': 11,
 'PHI': 13,
 'PIT': 12,
 'SEA': 29,
 'SJS': 26,
 'STL': 24,
 'TBL': 7,
 'TOR': 30,
 'UTA': 17,
 'VAN': 34,
 'VGK': 15,
 'WPG': 28,
 'WSH': 14}

In [ ]:
import requests

INSERT_QUERY = """
INSERT IGNORE INTO games
(
    game_id,
    season,
    game_type,
    game_date,
    home_team_id,
    away_team_id,
    home_score,
    away_score,
    game_state,
    venue_name
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

for team_abbrev, team_id in team_lookup.items():
    url = f"https://api-web.nhle.com/v1/club-schedule-season/{team_abbrev}/20252026"
    response = requests.get(url)
    print(team_abbrev, response.status_code)
    if response.status_code != 200:
        print("API Error:", response.text)
        continue
    data = response.json()
    for game in data.get("games", []):
        values = (
            game["id"],
            game["season"],
            game["gameType"],
            game["gameDate"],
            game["homeTeam"]["id"],
            game["awayTeam"]["id"],
            game["homeTeam"].get("score"),
            game["awayTeam"].get("score"),
            game.get("gameState"),
            game.get("venue", {}).get("default")
        )

        cursor.execute(INSERT_QUERY, values)

conn.commit()

ANA 200
BOS 200
BUF 200
CAR 200
CBJ 200
Central 404
API Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body>
<h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>https://api-web.nhle.com/v1/club-schedule-season/Central/20252026</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
</table>

</body>
</html>

CGY 200
CHI 200
COL 200
DAL 200
DET 200
EDM 200
FLA 200
LAK 200
MIN 200
MTL 200
NJD 200
NSH 200
NYI 200
NYR 200
OTT 200
PHI 200
PIT 200
SEA 200
SJS 200
STL 200
TBL 200
TOR 200
UTA 200
VAN 200
VGK 200
WPG 200
WSH 200
Games inserted successfully

In [23]:

cursor.execute("SELECT * FROM games")
records = cursor.fetchall()

In [24]:
import pandas as pd
df=pd.read_sql_query("select * from games",conn)
df

C:\Users\dines\AppData\Local\Temp\ipykernel_2492\2402511479.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("select * from games",conn)

,game_id,season,game_type,game_date,home_team_id,away_team_id,home_score,away_score,game_state,venue_name
0,2025010001,20252026,1,2025-09-21,26,24,3,1,FINAL,Toyota Arena
1,2025010002,20252026,1,2025-09-21,22,20,2,3,FINAL,Rogers Place
2,2025010003,20252026,1,2025-09-21,20,22,0,3,FINAL,Scotiabank Saddledome
3,2025010004,20252026,1,2025-09-21,18,13,5,0,FINAL,Bridgestone Arena
4,2025010005,20252026,1,2025-09-21,18,13,5,3,FINAL,Bridgestone Arena
...,...,...,...,...,...,...,...,...,...,...
1057,2025030311,20252026,3,2026-05-21,12,8,2,6,OFF,Lenovo Center
1058,2025030312,20252026,3,2026-05-23,12,8,3,2,OFF,Lenovo Center
1059,2025030313,20252026,3,2026-05-25,8,12,2,3,OFF,Centre Bell
1060,2025030314,20252026,3,2026-05-27,8,12,0,4,OFF,Centre Bell
1061,2025030315,20252026,3,2026-05-29,12,8,6,1,OFF,Lenovo Center

In [ ]:
# TABLE  5: GAME STATS

In [14]:
df_games=pd.read_json('game_stats.json')
df_games

,stat_id,game_id,player_id,team_id,goals,assists,points,shots_on_goal,penalty_min,toi,plus_minus
0,1,2025010051,8480448,1,0,0,0,0,0,14:28,0
1,2,2025010051,8479525,1,0,0,0,0,0,18:48,-1
2,3,2025010051,8477492,1,0,1,1,0,0,18:57,1
3,6,2025010051,8477476,1,1,1,2,0,0,20:44,2
4,10,2025010051,8482947,1,1,0,1,0,0,12:48,1
...,...,...,...,...,...,...,...,...,...,...,...
47403,53923,2025021300,8476879,20,0,0,0,0,0,18:25,-1
47404,53924,2025021300,8476441,20,0,0,0,0,0,18:48,0
47405,53925,2025021300,8474563,20,0,1,1,0,0,22:20,1
47406,53926,2025021300,8479998,20,0,0,0,0,0,19:50,2
47407,53927,2025021300,8482730,20,0,0,0,0,0,22:39,0

In [18]:
import pymysql
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:13849#Datasci@localhost/proj1"
)

In [19]:
df_games.to_sql('game_stats',if_exists='replace',con=engine)

47408

# TABLE 6 :  skater_season_stats

In [20]:
df_games=pd.read_json('skater_season_stats.json')
df_games

,stat_id,player_id,season,team_id,games_played,goals,assists,points,plus_minus,penalty_min,shots,avg_toi
0,1,8470613,20252026,1,82.0,12.0,23.0,35.0,33.0,32.0,172.0,NaN
1,2,8475172,20252026,1,77.0,16.0,34.0,50.0,-30.0,30.0,213.0,NaN
2,3,8475754,20252026,1,81.0,33.0,32.0,65.0,15.0,36.0,186.0,NaN
3,4,8475768,20252026,1,50.0,11.0,15.0,26.0,5.0,8.0,82.0,NaN
4,5,8476312,20252026,1,79.0,5.0,26.0,31.0,42.0,91.0,128.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
709,710,8483678,20252026,32,70.0,3.0,7.0,10.0,-16.0,39.0,46.0,NaN
710,711,8483768,20252026,32,24.0,0.0,3.0,3.0,-12.0,7.0,14.0,NaN
711,712,8484136,20252026,32,66.0,13.0,6.0,19.0,-13.0,26.0,62.0,NaN
712,713,8484240,20252026,32,70.0,5.0,16.0,21.0,-23.0,28.0,59.0,NaN
713,714,8484798,20252026,32,76.0,6.0,20.0,26.0,-33.0,41.0,73.0,NaN

In [22]:
df_games.to_sql('skater_season_stats',if_exists='replace',con=engine)

714

In [ ]:
#Table 7: goalie_season_stats

In [23]:

df_games=pd.read_json('goalie_season_stats.json')
df_games

,stat_id,player_id,season,team_id,games_played,wins,losses,ot_losses,save_pct,goals_against_avg,shutouts,saves
0,1,8475809,20252026,1,45.0,31.0,6.0,6.0,0.921317,NaN,4.0,NaN
1,2,8478406,20252026,1,39.0,23.0,10.0,2.0,0.903537,NaN,3.0,NaN
2,3,8481611,20252026,2,9.0,6.0,2.0,0.0,0.899471,NaN,1.0,NaN
3,4,8483548,20252026,2,39.0,31.0,6.0,2.0,0.894737,NaN,2.0,NaN
4,5,8479193,20252026,3,30.0,15.0,8.0,6.0,0.906579,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
76,77,8481519,20252026,31,55.0,19.0,25.0,11.0,0.902085,NaN,3.0,NaN
77,78,8482821,20252026,31,26.0,8.0,13.0,3.0,0.879845,NaN,1.0,NaN
78,79,8477967,20252026,32,20.0,8.0,10.0,1.0,0.896887,NaN,1.0,NaN
79,80,8480947,20252026,32,47.0,11.0,27.0,5.0,0.875486,NaN,0.0,NaN
80,81,8484268,20252026,32,21.0,6.0,11.0,2.0,0.881443,NaN,0.0,NaN

In [25]:
df_games.to_sql(' goalie_season_stats',if_exists='replace',con=engine)

81